# Use Alpine Linux
FROM alpine:latest

# Maintainer
LABEL  42_Barcelona_Cibersecurity_Bootcamp = luismiguelcasadodiaz@gmail.com 
USER root

#install ft_onion required packages
# --no-cache avoid index dowload
RUN apk update && \
	apk upgrade && \
	apk add --no-cache openrc && \
	apk add --no-cache openssh && \
	apk add --no-cache doas && \
	apk add --no-cache nginx 

# Preparation of daemons manager
RUN openrc
RUN touch /run/openrc/softlevel

# ssh config
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN rc-update add sshd
EXPOSE 22

RUN hostname -s nginx_server
ENV USER admin_nginx





#create user "admin_nginx- with home directory"
RUN adduser  -h /home/$USER -s /bin/sh -g "Administrador nginx" $USER; 
RUN echo -n $USER':123' :chpasswd
RUN addgroup $USER wheel
